# Generated by Django 5.1.6 on 2025-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='customer_birth_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debt',
            field=models.IntegerField(),
        ),
    ]
